# Generated by Django 3.0.2 on 2020-01-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Python', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Equipamento',
        ),
    ]
