# Generated by Django 3.0.2 on 2020-01-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Python', '0002_auto_20200108_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='nome',
            new_name='mac',
        ),
    ]
