# Generated by Django 3.0.2 on 2020-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Python', '0003_auto_20200108_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='id',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='mac',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
