# Generated by Django 3.0.2 on 2020-01-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Python', '0004_auto_20200108_1346'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equipamento',
            managers=[
            ],
        ),
    ]
