# Generated by Django 3.0.2 on 2020-01-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Python', '0005_auto_20200108_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='mac',
            new_name='MAC',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='tempo_de_servico',
        ),
    ]
