# Generated by Django 3.0.2 on 2020-01-09 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Python', '0006_auto_20200109_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='Numero_Patrimonio',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
